CREATE TABLE CATEGORIA (
 cod_categoria NUMBER(2) NOT NULL,
 nome VARCHAR2(50) NOT NULL,
 cod_categoria_pai NUMBER(2)
);

ALTER TABLE CATEGORIA ADD CONSTRAINT PK_CATEGORIA PRIMARY KEY (cod_categoria);

CREATE INDEX idx_cat_nome ON CATEGORIA (nome);
CREATE INDEX ifk_cat_cat ON CATEGORIA (cod_categoria_pai);


CREATE TABLE CLIENTE (
 cod_cliente NUMBER(5) NOT NULL,
 nome VARCHAR2(100) NOT NULL,
 data_cadastro DATE NOT NULL,
 tipo CHAR(1) NOT NULL
);

ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (cod_cliente);

CREATE INDEX idx_cli_nome ON CLIENTE (nome);


CREATE TABLE ESTADO (
 uf CHAR(2) NOT NULL,
 nome VARCHAR2(50) NOT NULL,
 regiao CHAR(2) NOT NULL
);

ALTER TABLE ESTADO ADD CONSTRAINT PK_ESTADO PRIMARY KEY (uf);

CREATE INDEX idx_est_nome ON ESTADO (nome);


CREATE TABLE FUNCIONARIO (
 matricula NUMERIC(5) NOT NULL,
 nome VARCHAR2(50) NOT NULL,
 email VARCHAR2(100) NOT NULL,
 situacao CHAR(2) NOT NULL
);

ALTER TABLE FUNCIONARIO ADD CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (matricula);


CREATE TABLE PEDIDO (
 num_pedido NUMBER(10) NOT NULL,
 data_emissao DATE NOT NULL,
 cod_cliente NUMBER(5) NOT NULL,
 matricula NUMERIC(5)
);

ALTER TABLE PEDIDO ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (num_pedido);

CREATE INDEX ifk_ped_cli ON PEDIDO (cod_cliente);


CREATE TABLE PESSOA_JURIDICA (
 cod_cliente NUMBER(5) NOT NULL,
 cnpj CHAR(18) NOT NULL,
 razao_social VARCHAR2(100) NOT NULL
);

ALTER TABLE PESSOA_JURIDICA ADD CONSTRAINT PK_PESSOA_JURIDICA PRIMARY KEY (cod_cliente);

CREATE UNIQUE INDEX ak_pj_cnpj ON PESSOA_JURIDICA (cnpj);


CREATE TABLE PRODUTO (
 cod_produto NUMBER(3) NOT NULL,
 nome VARCHAR2(100) NOT NULL,
 data_lancamento DATE NOT NULL,
 importado CHAR(1) NOT NULL,
 preco NUMBER(8,2) NOT NULL,
 prazo_entrega NUMBER(3) NOT NULL,
 cod_categoria NUMBER(2) NOT NULL,
 quantidade_estoque NUMBER(5)
);

ALTER TABLE PRODUTO ADD CONSTRAINT PK_PRODUTO PRIMARY KEY (cod_produto);

CREATE INDEX idx_prod_nome ON PRODUTO (nome);
CREATE INDEX ifk_prod_cat ON PRODUTO (cod_categoria);


CREATE TABLE CIDADE (
 cod_cidade NUMBER(5) NOT NULL,
 nome VARCHAR2(80) NOT NULL,
 uf CHAR(2) NOT NULL
);

ALTER TABLE CIDADE ADD CONSTRAINT PK_CIDADE PRIMARY KEY (cod_cidade);

CREATE INDEX idx_cid_nome ON CIDADE (nome);
CREATE INDEX ifk_cid_est ON CIDADE (uf);


CREATE TABLE ENDERECO (
 cod_endereco NUMERIC(2) NOT NULL,
 rua VARCHAR2(80) NOT NULL,
 numero NUMBER(6) NOT NULL,
 complemento VARCHAR2(20),
 cep NUMBER(8) NOT NULL,
 cod_cidade NUMBER(5) NOT NULL,
 cod_cliente NUMBER(5) NOT NULL
);

ALTER TABLE ENDERECO ADD CONSTRAINT PK_ENDERECO PRIMARY KEY (cod_endereco);

CREATE INDEX ifk_end_cid ON ENDERECO (cod_cidade);


CREATE TABLE ENTREGA (
 num_entrega NUMBER(10) NOT NULL,
 data DATE NOT NULL,
 placa CHAR(8) NOT NULL,
 mot_cnh NUMBER(11) NOT NULL,
 mot_nome VARCHAR2(100) NOT NULL,
 cod_endereco NUMERIC(2)
);

ALTER TABLE ENTREGA ADD CONSTRAINT PK_ENTREGA PRIMARY KEY (num_entrega);

CREATE INDEX idx_entr_placa ON ENTREGA (placa);
CREATE INDEX idx_entr_motnome ON ENTREGA (mot_nome);


CREATE TABLE FORNECEDOR (
 cod_fornecedor NUMERIC(2) NOT NULL,
 nome VARCHAR2(100) NOT NULL,
 e-mail VARCHAR2(100) NOT NULL
);

ALTER TABLE FORNECEDOR ADD CONSTRAINT PK_FORNECEDOR PRIMARY KEY (cod_fornecedor);


CREATE TABLE ITEM_PEDIDO (
 num_pedido NUMBER(10) NOT NULL,
 cod_produto NUMBER(3) NOT NULL,
 quantidade NUMBER(4),
 num_entrega NUMBER(10)
);

ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT PK_ITEM_PEDIDO PRIMARY KEY (num_pedido,cod_produto);

CREATE UNIQUE INDEX ak_itens_pedidos ON ITEM_PEDIDO (num_pedido,cod_produto);

CREATE INDEX ifk_itped_prod ON ITEM_PEDIDO (cod_produto);
CREATE INDEX ifk_itped_entr ON ITEM_PEDIDO (num_entrega);


CREATE TABLE PESSOA_FISICA (
 cod_cliente NUMBER(5) NOT NULL,
 cpf CHAR(14) NOT NULL,
 data_nascimento DATE NOT NULL,
 genero CHAR(1) NOT NULL,
 cod_empresa NUMBER(5)
);

ALTER TABLE PESSOA_FISICA ADD CONSTRAINT PK_PESSOA_FISICA PRIMARY KEY (cod_cliente);

CREATE UNIQUE INDEX ak_pf_cpf ON PESSOA_FISICA (cpf);

CREATE INDEX ifk_pf_pj ON PESSOA_FISICA (cod_empresa);


CREATE TABLE PRODUTO_FORNECEDOR (
 cod_produto NUMBER(3) NOT NULL,
 cod_fornecedor NUMERIC(2) NOT NULL,
 disponibilidade CHAR(1) NOT NULL
);

ALTER TABLE PRODUTO_FORNECEDOR ADD CONSTRAINT PK_PRODUTO_FORNECEDOR PRIMARY KEY (cod_produto,cod_fornecedor);


CREATE TABLE TELEFONE (
 id_telefone NUMBER NOT NULL,
 ddd NUMBER(2) NOT NULL,
 numero NUMBER(9) NOT NULL,
 cod_cliente NUMBER(5) NOT NULL
);

ALTER TABLE TELEFONE ADD CONSTRAINT PK_TELEFONE PRIMARY KEY (id_telefone);

CREATE INDEX ifk_tel_pf ON TELEFONE (cod_cliente);


ALTER TABLE CATEGORIA ADD CONSTRAINT FK_CATEGORIA_0 FOREIGN KEY (cod_categoria_pai) REFERENCES CATEGORIA (cod_categoria);


ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_0 FOREIGN KEY (cod_cliente) REFERENCES CLIENTE (cod_cliente);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_1 FOREIGN KEY (matricula) REFERENCES FUNCIONARIO (matricula);


ALTER TABLE PESSOA_JURIDICA ADD CONSTRAINT FK_PESSOA_JURIDICA_0 FOREIGN KEY (cod_cliente) REFERENCES CLIENTE (cod_cliente);


ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_0 FOREIGN KEY (cod_categoria) REFERENCES CATEGORIA (cod_categoria);


ALTER TABLE CIDADE ADD CONSTRAINT FK_CIDADE_0 FOREIGN KEY (uf) REFERENCES ESTADO (uf);


ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_0 FOREIGN KEY (cod_cidade) REFERENCES CIDADE (cod_cidade);
ALTER TABLE ENDERECO ADD CONSTRAINT FK_ENDERECO_1 FOREIGN KEY (cod_cliente) REFERENCES CLIENTE (cod_cliente);


ALTER TABLE ENTREGA ADD CONSTRAINT FK_ENTREGA_0 FOREIGN KEY (cod_endereco) REFERENCES ENDERECO (cod_endereco);


ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT FK_ITEM_PEDIDO_0 FOREIGN KEY (num_pedido) REFERENCES PEDIDO (num_pedido);
ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT FK_ITEM_PEDIDO_1 FOREIGN KEY (cod_produto) REFERENCES PRODUTO (cod_produto);
ALTER TABLE ITEM_PEDIDO ADD CONSTRAINT FK_ITEM_PEDIDO_2 FOREIGN KEY (num_entrega) REFERENCES ENTREGA (num_entrega);


ALTER TABLE PESSOA_FISICA ADD CONSTRAINT FK_PESSOA_FISICA_0 FOREIGN KEY (cod_cliente) REFERENCES CLIENTE (cod_cliente);
ALTER TABLE PESSOA_FISICA ADD CONSTRAINT FK_PESSOA_FISICA_1 FOREIGN KEY (cod_empresa) REFERENCES PESSOA_JURIDICA (cod_cliente);


ALTER TABLE PRODUTO_FORNECEDOR ADD CONSTRAINT FK_PRODUTO_FORNECEDOR_0 FOREIGN KEY (cod_produto) REFERENCES PRODUTO (cod_produto);
ALTER TABLE PRODUTO_FORNECEDOR ADD CONSTRAINT FK_PRODUTO_FORNECEDOR_1 FOREIGN KEY (cod_fornecedor) REFERENCES FORNECEDOR (cod_fornecedor);


ALTER TABLE TELEFONE ADD CONSTRAINT FK_TELEFONE_0 FOREIGN KEY (cod_cliente) REFERENCES PESSOA_FISICA (cod_cliente);


